### ISSUE TITLE
Issues Compiling NTuple

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple#11]
I cloned the NTuple code onto my machine and modified the Makefile as needed. When I run `make` however, I get the following error. 

```
NTuple.cc:19:20: error: ‘inputFileNames’ was not declared in this scope 
vector<string> inputFileNames;  

NTuple.cc:21:12: error: expected ‘;’ before ‘outputFileName’ 
string outputFileName ="Converted.root";

NTuple.cc:22:69: error: ‘outputFileName’ was not declared in this scope
interface.Add("-of","output file (default = 'Converted.root')",&outputFileName);

make: *** [NTuple] Error 1
rm Griffin.o Settings.o Converter.o
```

I am unsure of what to do next. Thanks in advance!

**Comment by VinzenzBildstein** [comment]
Thanks for raising this issue, there was a problem in NTuple.cc where the std namespace wasn't used. This is fixed now together with a few compiler warnings (see PR #12).
If this works for you @cnatzke, please close the issue.
