### ISSUE TITLE
NTuple Error

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple#13]
I installed CommandLineInterface according to the README and it created a directory in my home directory titled `lib` with `libCommandLineInterface.so` present inside the `~/lib` directory. I then installed NTuple, modifying the Makefile accordingly, and NTuple compiled successfully (No errors). However when I run NTuple via `~/Programs/NTuple/NTuple -if g4out.root -sf Settings.dat`, I get an error on the output stating: 
`~/Programs/NTuple/NTuple: error while loading shared libraries: libCommandLineInterface.so: cannot open shared object file: No such file or directory`

Sorry for the inconvenience but I am unsure of what I did incorrectly or how to fix this issue. Thanks in advance!

**Comment by VinzenzBildstein** [comment]
I think you need to add ~/lib (or $HOME/lib) to your PATH environment variable.

**Comment by cnatzke** [comment]
Do you mean in the Makefile or when I try use the NTuple command?

**Comment by VinzenzBildstein** [comment]
In the terminal where you use the command. You can add that line to your .profile (or .bash_profile).

**Comment by cnatzke** [comment]
That line already exists within my `.bash_profile`. It currently has 
` PATH=$PATH:$HOME/.local/bin:$HOME/bin ` . I am still getting the same error.

**Comment by VinzenzBildstein** [comment]
Ah, sorry, of course you don't need to add the path to your PATH variable, but to the LD_LIBRARY_PATH variable.

**Comment by VinzenzBildstein** [comment]
So put something like 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
in your profile

**Comment by cnatzke** [comment]
Should I rebuild NTuple after adding the LD_LIBRARY_PATH?

**Comment by cnatzke** [comment]
I put the LD_LIBRARY_PATH variable in my profile and I am still receiving the original error. I did rebuilt NTuple just in case.

**Comment by VinzenzBildstein** [comment]
It should work w/o rebuilding. What is the output if from ldd (just type 'ldd NTuple' in the NTuple-Directory)?

**Comment by VinzenzBildstein** [comment]
Just to clarify, if you only put the line into your profile and didn't execute it on the command-line, you need to either log out and back in, or source your profile. To be sure, what's the output of 'echo $LD_LIBRARY_PATH'?

**Comment by cnatzke** [comment]
Source .bash_profile fixed the issue! Thanks!
