### ISSUE TITLE
Error Compiling NTuple

### ISSUE THREAD

**Issue by CANFSA** [GRIFFINCollaboration/NTuple#18]
When trying to compile NTuple, I am getting the fatal error "Utilities.hh: No such file or directory"
I'm not sure why I am getting this error, I'm wondering if there a step I skipped somehow that would have placed that file in the right place.

**Comment by AndrewMac1** [comment]
When compiling did you compile command line interface first?

**Comment by AndrewMac1** [comment]
To compile NTuple you have to fork CommandLineInterface and compile that first, then compile NTuple.

**Comment by CANFSA** [comment]
Yes I compiled the CommandLineInterface first. What do you mean fork it?

C. Gus Becker
B.S. Engineering Physics 2017
Colorado School of Mines

**Comment by VinzenzBildstein** [comment]
If you've compiled it, does the COMM_DIR variable in the makefile of NTuple point to the right directory? And does Utilities.hh exist in that directory?

**Comment by CANFSA** [comment]
That was the issue. Thanks!

C. Gus Becker
B.S. Engineering Physics 2017
Colorado School of Mines


On Wed, Mar 15, 2017 at 8:33 AM, Vinzenz Bildstein <notifications@github.com
