### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple#19]
I am trying to run a g4out.root file from the GRIFFIN Sim through NTuple and I get the following error, 

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
```
What does this error mean and where can I fix it?

Cheers,
cnatzke

**Comment by r3dunlop** [comment]
You are trying to access the i-th element of a vector when there are <i elements in that vector. An easyish way to track it would be to catch the exception, but you need to know how to use exceptions to make that the easy way. The other way would be to just put cout statements everywhere you access a vector and see which one kills it. I believe it also has to be using the `.at()` vector method to throw this exception and the `[]` accessor will not throw this.

**Comment by cnatzke** [comment]
I found some more information. This error is only thrown when I add in a new geometry to the GRIFFIN Simulation. If I do not activate that geometry, there is no problem and NTUPLE works fine. Any idea why/where this would cause an error?

**Comment by AndrewMac1** [comment]
If you run with just your new volume and exclude GRIFFIN is there issues? Is the errors something new or does it throw the same error you posted before? If it is something new could you post the new error.

**Comment by jturko** [comment]
Have to made sure that you are resizing all the fResolution, fThreshold, etc variables for your added geometry? This is done in the Settings.cc file around line 40.

**Comment by cnatzke** [comment]
@jturko I don't imagine that is a problem since the geometry I added is not a detector, but rather a source holder (essentially a Delrin cyclinder that extends to the centre of the array). Also the error is thrown from the Converter.cc call instead of the Settings.cc call. I put a print statement after the Settings call and it ran fine.

**Comment by cnatzke** [comment]
@AndrewMac1 When I run the simulation with only my source holder geometry, there is no error in NTUPLE because there is no data in the input ROOT file. Since the added geometry is not a detector, I did not have the simulation record events inside of it, and I imagine this is why the g4out.root has not data.

**Comment by VinzenzBildstein** [comment]
Try and run the program with gdb. When it crashes type ```bt``` for the back trace. This should give you a line number in the code where it crashes. You can then use that to narrow down where the error comes from.

**Comment by cnatzke** [comment]
The output of gdb is as follows: 
```
Resolution (en=<optimized out>, crystalID=4, detectorID=9, systemID=1000, this=<optimized out>)
at Settings.hh:69

Converter::Run (this=this@entry=0x7fffffff25e0) at Converter.cc:1373

```
The first error is the fResolution and fThreshold parameters  for the LaBr detectors. I used the LaBr geometry files as templates for my new geometry. The second (Converter.cc) is a smeared energy variable.  What are these variables doing and why would the addition of a new non-detector geometry cause this to fail?

**Comment by VinzenzBildstein** [comment]
Well, now that you know where the error happens, you could put some cout statements before those lines, telling you which element you're trying to access and what the length of the vector is. Once you have that you can check where the index comes from, i.e. on what settings the limit of the index is based on, and figure out why that might be wrong.

**Comment by cnatzke** [comment]
I don't think this is a problem with NTUPLE on further investigation. The loop that fails is simply looping through the events, and it fails on event 3 (out of 10^7). Furthermore, it only fails when I activate my new geometry. Thanks for all the help!

**Comment by r3dunlop** [comment]
I mean, it seems like it’s failing when you access that vector of a vector on getting the resolution. Are you trying to access a resolution (for your new geometry) that doesn’t exist? That would be my guess.

**Comment by r3dunlop** [comment]
Try changing the code to this:
```c++
    double Resolution(int systemID, int detectorID, int crystalID, double en) {
        if(fResolution.find(systemID) != fResolution.end()) {
            try{
                  return fResolution[systemID].at(detectorID).at(crystalID).Eval(en);
             }
             catch (const std::out_of_range& e) {
                 std::cout << "Out of Range error, detID = " << detectorID << " CrystalID = " << crystalID << std::endl;
             }
        }
        return 0.;
    }
```
And adjust the catch statement appropriately to identify the issue with your bad event. 
Edit: You may or may not have to include the stdexcept.h header

**Comment by cnatzke** [comment]
That could be it. My new geometry is a source holder, so it is not actually a detector; its basically a plastic cylinder. I have not set a threshold value for it. The resolution values rely on a SystemID value (e.g. 1000, 5000, etc), do you know where those values come from?

**Comment by r3dunlop** [comment]
I have no clue, I really know nothing about this code... but if you use a system ID that doesn't show up in the fResolution map, it just returns a resolution of 0. This means that you are either using a systemID that exists in the map already, or you are creating your own map entry.

**Comment by VinzenzBildstein** [comment]
According to a quick grep, the system ID is read from the tree. So it is being set in the simulation. Using grep in the simulation source code shows that this is being set in the stepping action. Did you change it accordingly when you created your new system?

**Comment by cnatzke** [comment]
I did not, I am going to try implementing the geometry differently in the Simulation, then if that doesn't work I will try setting thresholds.

**Comment by r3dunlop** [comment]
I’m not sure what “setting thresholds" means as I’m not really familiar with the code, but I would suggest you fix the ID properly instead of hacking in a fix such as thresholding away a resolution call. Doing a quick hack fix where you aren’t putting something in as intended, but use another piece of code to block it, is a sure fire way to get hard-to-find bugs (or worse, unknown bugs) later down the road. Especially if someone else needs to use your code at any point.

**Comment by cnatzke** [comment]
Good advice, thanks! The issue is there should be no reason this error is being thrown. The line that is throwing the error in NTUPLE is due to a detector resolution, threshold, or similar problem (I think). What I have added to the simulation is not a scoring volume, but rather something like the 8pi vacuum chamber. All it is meant to do is add material for the decaying ions to interact with. I have no idea why NTUPLE would need to be modified when I am essentially adding a support structure. My current guess is the problem lies in the simulation rather than NTUPLE since NTUPLE works fine for the exact same simulation just without the new geometry activated.

**Comment by cnatzke** [comment]
Fixed it. My new geometry was classified as a detector system in the simulation instead of an apparatus. Now that its classified correctly everything works no problem. Thanks again for all of the help. 
Cheers, 
cnatzke
