### ISSUE TITLE
Not finding shared libraries

### ISSUE THREAD

**Issue by CharliePaxman** [GRIFFINCollaboration/NTuple#21]
Hello,

I am having a problem using NTuple, where it seems unable to find the libraries it shares with CommandLineInterface. I have cloned the files into the locations;

_/home/cpaxman/packages/CommandLineInterface
/home/cpaxman/packages/NTuple_

I then run make clean & make in CommandLineInterface, and then NTuple. Then, when trying to run _/home/cpaxman/packages/NTuple/NTuple -if g4out.root -sf /home/cpaxman/packages/NTuple/Settings.dat_, I get the following error;

**_/home/cpaxman/packages/NTuple/NTuple: error while loading shared libraries: libCommandLineInterface.so: cannot open shared object file: No such file or directory_**

When I check the content of ~/lib, the libraries are there. 

_lrwxrwxrwx. 1 cpaxman users     50 Oct 21 15:49 libCommandLineInterface.so -> /home/cpaxman/lib/libCommandLineInterface.so.1.0.1
-rwxr-xr-x. 1 cpaxman users 638840 Oct 21 15:49 libCommandLineInterface.so.1.0.1
lrwxrwxrwx. 1 cpaxman users     44 Oct 21 15:49 libTextAttributes.so -> /home/cpaxman/lib/libTextAttributes.so.1.0.1
-rwxr-xr-x. 1 cpaxman users  20872 Oct 21 15:49 libTextAttributes.so.1.0.1
lrwxrwxrwx. 1 cpaxman users     39 Oct 21 15:49 libUtilities.so -> /home/cpaxman/lib/libUtilities.so.1.0.1
-rwxr-xr-x. 1 cpaxman users 189672 Oct 21 15:49 libUtilities.so.1.0.1_

I have tried adding ~/lib to my PATH variable, and I have tried cloning the two files into various locations (such as directly into ~/). The LIBDIR variable in both Makefiles is the same.

What am I missing here?

Thanks!
Charlotte

**Comment by VinzenzBildstein** [comment]
Did you add ~/lib to your LD_LIBRARY_PATH ?

**Comment by CharliePaxman** [comment]
That worked, thank you!
