### ISSUE TITLE
seg fault when using new forked NTuple 

### ISSUE THREAD

**Issue by AndrewMac1** [GRIFFINCollaboration/NTuple#5]
I forked a new version of NTuple yesterday and when I ran it on a small sim (10^5 events) I got a seg fault saying the following:

Warning in TChain::GetEntries: PROOF proxy not up-to-date: run TChain::SetProof(kTRUE, kTRUE) first

I was able to run through this with the older version I was running and it worked fine I could see all the histograms so I know it wasn't the simulation. I used the same Settings.dat for both so I am unsure where the seg fault is coming from. Does anyone else see this?

**Comment by evan012345** [comment]
Hey Andrew,
Can you send me your g4out.root file and Settings file so I can confirm this on my end?
And how old is your "older version" of NTuple?

**Comment by AndrewMac1** [comment]
Hey Evan,

It may be easier if I just tell you where the files are. My root file is /nessa/geant4/andrew/test/g4out.root and the data file is in /nessa/geant4/andrew/test/With3D/Settings.dat. The older version I was using was before the descant portion was implemented, so fairly old but no real changes that should have affected the portion of the code I am using I don't believe. 

Cheers,
Andrew 

----- Original Message -----

**Comment by evan012345** [comment]
I can't reproduce your error. It runs fine for me, see attached image. 

hmmmmm.... Stupid question, but have you tried making clean your NTuple code and re-making it. Maybe your linking to old libraries? If that doesn't solve it we need to understand this TChain error better. Is Ryan there, has he seen this before?

![image](https://cloud.githubusercontent.com/assets/5274522/10944036/2b4bcb78-82e5-11e5-8944-8c5b689cbbf7.png)

**Comment by AndrewMac1** [comment]
Yeah the first thing I did was a make clean all three (ascii, command line and ntuple) then make (command line, then ascii and finally ntuple). Ryan isn't in at the moment, I don't think he is coming in today.  

----- Original Message -----

**Comment by evan012345** [comment]
And your running on nessa or your own computer?

**Comment by AndrewMac1** [comment]
I just did another make clean and make (sanity check) got the same thing. I am just going try to clone it again, just as a double check I didn't do something weird.

----- Original Message -----

**Comment by AndrewMac1** [comment]
I am running on nessa. Ok...I don't know what happened but when I got another clone and did a make clean/make the same way as before it seems to be fine now. I have no idea what was happening before so now I am confused, but at least everything is functioning. 

----- Original Message -----

**Comment by evan012345** [comment]
Okay, good.
